"""Local job execution for run command."""

from pathlib import Path
from typing import Any

from epycloud.lib.command_helpers import generate_run_id, get_docker_config
from epycloud.lib.output import error, info, success

from ..validation import (
    add_stage_specific_info,
    build_base_confirmation_info,
    prompt_user_confirmation,
)
from .docker_compose import build_env_from_config, run_docker_compose_stage


def run_job_local(
    ctx: dict[str, Any],
    config: dict[str, Any],
    stage: str,
    exp_id: str,
    run_id: str | None,
    task_index: int,
    num_tasks: int | None,
    output_config: str | None,
    auto_confirm: bool,
    verbose: bool,
    dry_run: bool,
    project_directory: Path,
) -> int:
    """Run individual job locally with docker compose.

    Parameters
    ----------
    ctx : dict[str, Any]
        Command context
    config : dict[str, Any]
        Configuration dict
    stage : str
        Stage (A, B, or C)
    exp_id : str
        Experiment ID
    run_id : str | None
        Run ID
    task_index : int
        Task index for stage B
    num_tasks : int | None
        Number of tasks for stage C
    output_config : str | None
        Output config filename for Stage C (e.g., "output_projection.yaml")
    auto_confirm : bool
        Auto-confirm without prompting
    verbose : bool
        Verbose output
    dry_run : bool
        Dry run mode
    project_directory : Path
        Absolute path to Docker Compose project directory

    Returns
    -------
    int
        Exit code
    """
    # Get config values
    docker = get_docker_config(config)
    image_name = docker["image_name"]
    # For local runs, default to 'local' tag (matches docker-compose.yml)
    image_tag = docker.get("image_tag") or "local"
    if image_tag == "latest":
        image_tag = "local"
    pipeline = config.get("pipeline", {})
    dir_prefix = pipeline.get("dir_prefix", "pipeline/flu/")

    # Auto-generate run_id for stage A if not provided
    if stage == "A" and not run_id:
        run_id = generate_run_id()

    # Build storage path
    run_id_display = run_id if run_id else "<auto-generated>"
    storage_path = f"./local/bucket/{dir_prefix}{exp_id}/{run_id_display}/"

    # Build confirmation info
    confirmation_info = build_base_confirmation_info(
        ctx, "job", exp_id, run_id if run_id else "<auto-generated>"
    )
    confirmation_info.update(
        {
            "storage_path": storage_path,
            "stage": stage,
            "image_name": image_name,
            "image_tag": image_tag,
        }
    )
    add_stage_specific_info(confirmation_info, stage, task_index, num_tasks, output_config)

    # Show confirmation and prompt
    if not prompt_user_confirmation(auto_confirm, confirmation_info, mode="local"):
        return 0

    info(f"Running Stage {stage} locally with Docker Compose...")
    info(f"Experiment ID: {exp_id}")
    if run_id:
        info(f"Run ID: {run_id}")
    info(f"Project directory: {project_directory}")

    # Build base environment variables from config
    base_env = build_env_from_config(config)

    # Determine service and add runtime-specific env vars
    if stage == "A":
        service = "builder"
        runtime_vars = {"EXP_ID": exp_id, "RUN_ID": run_id}
    elif stage == "B":
        service = "runner"
        runtime_vars = {
            "EXP_ID": exp_id,
            "RUN_ID": run_id,
            "TASK_INDEX": str(task_index),
        }
    else:  # C
        service = "output"
        runtime_vars = {
            "EXP_ID": exp_id,
            "RUN_ID": run_id,
            "NUM_TASKS": str(num_tasks),
            "OUTPUT_CONFIG_FILE": output_config or "",
        }

    # Merge base config env vars with runtime vars (runtime vars take precedence)
    env_vars = {**base_env, **runtime_vars}

    result = run_docker_compose_stage(
        project_directory=project_directory,
        service=service,
        env_vars=env_vars,
        dry_run=dry_run,
    )

    if result == 0:
        success(f"Stage {stage} completed successfully")
        info(f"Results in: ./local/bucket/{dir_prefix}{exp_id}/{run_id}/")
    else:
        error(f"Stage {stage} failed")

    return result
