"""Unit tests for confirmation prompt formatting."""

from unittest.mock import patch

import pytest

from epycloud.utils.confirmation import (
    _format_job_details,
    _format_workflow_details,
    _heading,
    format_confirmation,
    prompt_confirmation,
)


@pytest.fixture(autouse=True)
def no_color():
    """Disable color output for all tests in this module."""
    with patch("epycloud.lib.output.supports_color", return_value=False):
        yield


@pytest.fixture
def cloud_workflow_info():
    """Cloud workflow confirmation info (mirrors cloud/workflow.py)."""
    return {
        "command_type": "workflow",
        "exp_id": "test-flu",
        "run_id": "20250101-120000-abc123",
        "environment": "dev",
        "profile": "flu",
        "project_id": "my-project",
        "region": "us-central1",
        "bucket_name": "my-bucket",
        "storage_path": "gs://my-bucket/pipeline/flu/test-flu/20250101-120000-abc123/",
        "modeling_suite_repo": "mobs-lab/epymodelingsuite",
        "modeling_suite_ref": "main",
        "forecast_repo": "mobs-lab/flu-forecast",
        "forecast_repo_ref": "develop",
        "pat_configured": True,
        "max_parallelism": 50,
        "task_count_per_node": 1,
        "stage_a_machine_type": "",
        "stage_a_machine_type_override": None,
        "stage_a_cpu_milli": 2000,
        "stage_a_memory_mib": 8192,
        "stage_a_max_run_duration": 3600,
        "stage_b_machine_type": "e2-highmem-4",
        "stage_b_machine_type_override": "e2-highmem-4",
        "stage_b_cpu_milli": 4000,
        "stage_b_memory_mib": 32768,
        "stage_b_max_run_duration": 36000,
        "stage_c_machine_type": "",
        "stage_c_machine_type_override": None,
        "stage_c_cpu_milli": 2000,
        "stage_c_memory_mib": 8192,
        "stage_c_max_run_duration": 7200,
        "skip_output": False,
        "output_config": "output_projection.yaml",
        "image_uri": "us-central1-docker.pkg.dev/my-project/repo/epymodelingsuite:latest",
        "image_tag": "latest",
    }


@pytest.fixture
def cloud_job_info():
    """Cloud job confirmation info (mirrors cloud/job.py)."""
    return {
        "command_type": "job",
        "exp_id": "test-flu",
        "run_id": "20250101-120000-abc123",
        "environment": "prod",
        "profile": "flu",
        "project_id": "my-project",
        "region": "us-east1",
        "stage": "B",
        "machine_type": "e2-standard-4",
        "max_duration_hours": 10,
        "image_uri": "us-central1-docker.pkg.dev/my-project/repo/epymodelingsuite:v1",
        "task_index": 3,
        "cpu_milli": 4000,
        "memory_mib": 16384,
        "task_count_per_node": 1,
    }


@pytest.fixture
def local_workflow_info():
    """Local workflow confirmation info."""
    return {
        "command_type": "workflow",
        "exp_id": "test-sim",
        "run_id": "<auto-generated>",
        "environment": "local",
        "profile": "flu",
        "skip_output": False,
        "output_config": None,
        "image_name": "epymodelingsuite",
        "image_tag": "dev",
        "storage_path": "./local/bucket/pipeline/flu/test-sim/",
    }


@pytest.fixture
def local_job_info():
    """Local job confirmation info."""
    return {
        "command_type": "job",
        "exp_id": "test-sim",
        "run_id": "20250101-000000-local",
        "environment": "local",
        "profile": "flu",
        "stage": "A",
        "image_name": "epymodelingsuite",
        "image_tag": "dev",
    }


class TestHeading:
    """Test _heading() section heading formatter."""

    def test_plain_text(self):
        """Test plain text output wraps in brackets."""
        assert _heading("Foo") == "[Foo]"

    def test_with_color(self):
        """Test color-enabled output contains ANSI codes."""
        with patch("epycloud.lib.output.supports_color", return_value=True):
            result = _heading("Bar")
        assert "\033[" in result
        assert "Bar" in result

    def test_empty_string(self):
        """Test empty string returns empty brackets."""
        assert _heading("") == "[]"


class TestFormatWorkflowDetails:
    """Test _format_workflow_details() output lines."""

    def test_always_shows_heading_and_ids(self):
        """Test heading, exp_id, and run_id always present."""
        lines = _format_workflow_details({}, "exp1", "run1", "cloud")
        assert lines[0] == "[Workflow Details]"
        assert "  Experiment ID: exp1" in lines
        assert "  Run ID: run1" in lines

    def test_cloud_shows_parallelism(self):
        """Test cloud mode shows max_parallelism and tasks_per_node."""
        info = {"max_parallelism": 50, "task_count_per_node": 2}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        assert "  Max parallelism: 50" in lines
        assert "  Tasks per node: 2" in lines

    def test_cloud_shows_all_stage_resources(self, cloud_workflow_info):
        """Test cloud mode shows resource lines for all 3 stages."""
        lines = _format_workflow_details(
            cloud_workflow_info, "test-exp", "test-run", "cloud"
        )
        resource_lines = [l for l in lines if l.startswith("  Stage ") and "mCPU" in l]
        assert len(resource_lines) == 3
        assert any("Stage A:" in l for l in resource_lines)
        assert any("Stage B:" in l for l in resource_lines)
        assert any("Stage C:" in l for l in resource_lines)

    def test_stage_skipped_when_cpu_none(self):
        """Test stage is omitted when cpu_milli is None."""
        info = {"stage_a_cpu_milli": None, "stage_b_cpu_milli": 4000, "stage_b_memory_mib": 8192}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        stage_lines = [l for l in lines if l.startswith("  Stage ")]
        assert not any("Stage A:" in l for l in stage_lines)
        assert any("Stage B:" in l for l in stage_lines)

    def test_machine_type_auto_when_empty(self):
        """Test empty machine type displays as 'auto'."""
        info = {
            "stage_a_cpu_milli": 2000,
            "stage_a_memory_mib": 8192,
            "stage_a_machine_type": "",
            "stage_a_max_run_duration": 3600,
        }
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        stage_a = [l for l in lines if "Stage A:" in l][0]
        assert "auto" in stage_a

    def test_override_marker(self):
        """Test ' *' marker appears when machine type is overridden."""
        info = {
            "stage_b_cpu_milli": 4000,
            "stage_b_memory_mib": 32768,
            "stage_b_machine_type": "e2-highmem-4",
            "stage_b_machine_type_override": "e2-highmem-4",
            "stage_b_max_run_duration": 36000,
        }
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        stage_b = [l for l in lines if "Stage B:" in l][0]
        assert " *" in stage_b

    def test_no_override_marker_when_not_overridden(self):
        """Test no ' *' marker when machine type is not overridden."""
        info = {
            "stage_b_cpu_milli": 4000,
            "stage_b_memory_mib": 32768,
            "stage_b_machine_type": "e2-highmem-4",
            "stage_b_machine_type_override": None,
            "stage_b_max_run_duration": 36000,
        }
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        stage_b = [l for l in lines if "Stage B:" in l][0]
        assert " *" not in stage_b

    def test_duration_conversion(self):
        """Test duration 3600s displays as 1.0h."""
        info = {
            "stage_a_cpu_milli": 1000,
            "stage_a_memory_mib": 4096,
            "stage_a_machine_type": "",
            "stage_a_max_run_duration": 3600,
        }
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        stage_a = [l for l in lines if "Stage A:" in l][0]
        assert "max 1.0h" in stage_a

    def test_duration_zero(self):
        """Test duration 0s displays as 0.0h."""
        info = {
            "stage_a_cpu_milli": 1000,
            "stage_a_memory_mib": 4096,
            "stage_a_machine_type": "",
            "stage_a_max_run_duration": 0,
        }
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        stage_a = [l for l in lines if "Stage A:" in l][0]
        assert "max 0.0h" in stage_a

    def test_skip_output_enabled(self):
        """Test skip_output=False shows 'enabled'."""
        info = {"skip_output": False}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        assert "  Stage C (output): enabled" in lines

    def test_skip_output_disabled(self):
        """Test skip_output=True shows 'disabled'."""
        info = {"skip_output": True}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        assert "  Stage C (output): disabled" in lines

    def test_output_config_shown(self):
        """Test output_config value is displayed."""
        info = {"output_config": "output_projection.yaml"}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        assert "  Output config: output_projection.yaml" in lines

    def test_output_config_omitted_when_none(self):
        """Test output_config line omitted when None."""
        info = {"output_config": None}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        assert not any("Output config" in l for l in lines)

    def test_output_config_omitted_when_empty(self):
        """Test output_config line omitted when empty string."""
        info = {"output_config": ""}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        assert not any("Output config" in l for l in lines)

    def test_cloud_shows_storage_path(self):
        """Test cloud mode shows storage_path."""
        info = {"storage_path": "gs://bucket/path/"}
        lines = _format_workflow_details(info, "test-exp", "test-run", "cloud")
        assert "  Storage path: gs://bucket/path/" in lines

    def test_local_no_parallelism(self):
        """Test local mode omits parallelism fields."""
        info = {"max_parallelism": 50, "task_count_per_node": 1}
        lines = _format_workflow_details(info, "test-exp", "test-run", "local")
        assert not any("Max parallelism" in l for l in lines)
        assert not any("Tasks per node" in l for l in lines)

    def test_local_no_stage_resources(self):
        """Test local mode omits per-stage resource lines."""
        info = {
            "stage_a_cpu_milli": 2000,
            "stage_a_memory_mib": 8192,
            "stage_a_machine_type": "",
            "stage_a_max_run_duration": 3600,
        }
        lines = _format_workflow_details(info, "test-exp", "test-run", "local")
        assert not any("Stage A:" in l for l in lines)

    def test_local_no_storage_path(self):
        """Test local mode omits storage_path."""
        info = {"storage_path": "gs://bucket/path/"}
        lines = _format_workflow_details(info, "test-exp", "test-run", "local")
        assert not any("Storage path" in l for l in lines)

    def test_local_shows_skip_output(self):
        """Test local mode still shows skip_output status."""
        info = {"skip_output": True}
        lines = _format_workflow_details(info, "test-exp", "test-run", "local")
        assert "  Stage C (output): disabled" in lines


class TestFormatJobDetails:
    """Test _format_job_details() output lines."""

    def test_shows_heading_and_ids(self):
        """Test heading, exp_id, and run_id always present."""
        info = {"stage": "A"}
        lines = _format_job_details(info, "exp1", "run1")
        assert lines[0] == "[Job Details]"
        assert "  Experiment ID: exp1" in lines
        assert "  Run ID: run1" in lines

    def test_stage_names(self):
        """Test A/B/C map to Builder/Runner/Output."""
        for letter, name in [("A", "Builder"), ("B", "Runner"), ("C", "Output")]:
            info = {"stage": letter}
            lines = _format_job_details(info, "test-exp", "test-run")
            assert f"  Stage: {letter} ({name})" in lines

    def test_unknown_stage(self):
        """Test unknown stage falls back to raw value."""
        info = {"stage": "X"}
        lines = _format_job_details(info, "test-exp", "test-run")
        assert "  Stage: X (X)" in lines

    def test_stage_b_shows_task_index(self):
        """Test Stage B includes task_index."""
        info = {"stage": "B", "task_index": 5}
        lines = _format_job_details(info, "test-exp", "test-run")
        assert "  Task index: 5" in lines

    def test_stage_b_does_not_show_num_tasks(self):
        """Test Stage B omits num_tasks even if present."""
        info = {"stage": "B", "task_index": 5, "num_tasks": 10}
        lines = _format_job_details(info, "test-exp", "test-run")
        assert not any("Num tasks" in l for l in lines)

    def test_stage_c_shows_num_tasks(self):
        """Test Stage C includes num_tasks."""
        info = {"stage": "C", "num_tasks": 10}
        lines = _format_job_details(info, "test-exp", "test-run")
        assert "  Num tasks: 10" in lines

    def test_stage_c_shows_output_config(self):
        """Test Stage C includes output_config."""
        info = {"stage": "C", "output_config": "output_calibration.yaml"}
        lines = _format_job_details(info, "test-exp", "test-run")
        assert "  Output config: output_calibration.yaml" in lines

    def test_stage_c_omits_empty_output_config(self):
        """Test Stage C omits output_config when empty."""
        info = {"stage": "C", "output_config": ""}
        lines = _format_job_details(info, "test-exp", "test-run")
        assert not any("Output config" in l for l in lines)

    def test_stage_a_does_not_show_task_index(self):
        """Test Stage A omits task_index even if present."""
        info = {"stage": "A", "task_index": 0}
        lines = _format_job_details(info, "test-exp", "test-run")
        assert not any("Task index" in l for l in lines)


class TestFormatConfirmation:
    """Test format_confirmation() assembly for each mode x command_type."""

    def test_cloud_workflow(self, cloud_workflow_info):
        """Test cloud workflow: header, sections, docker split, GitHub."""
        result = format_confirmation(cloud_workflow_info, "cloud")
        assert result.startswith("Submit workflow")
        # Expected sections
        assert "[Configuration]" in result
        assert "[Google Cloud]" in result
        assert "[GitHub]" in result
        assert "[Workflow Details]" in result
        assert "[Docker Image]" in result
        assert "[Resources]" not in result
        # Docker URI split
        assert "Registry: us-central1-docker.pkg.dev" in result
        assert "Image: my-project/repo/epymodelingsuite:latest" in result
        # GitHub info
        assert "mobs-lab/epymodelingsuite@main" in result
        assert "mobs-lab/flu-forecast@develop" in result

    def test_cloud_job(self, cloud_job_info):
        """Test cloud job: header, sections, resources."""
        result = format_confirmation(cloud_job_info, "cloud")
        assert result.startswith("Submit Runner job")
        # Expected sections
        assert "[Configuration]" in result
        assert "[Google Cloud]" in result
        assert "[Job Details]" in result
        assert "[Resources]" in result
        assert "[Docker Image]" in result
        assert "[GitHub]" not in result
        # Resources
        assert "Machine type: e2-standard-4" in result
        assert "CPU: 4000 mCPU" in result
        assert "Memory: 16384 MiB" in result

    def test_cloud_job_machine_type_auto_select(self, cloud_job_info):
        """Test empty machine type shows 'auto-select'."""
        cloud_job_info["machine_type"] = ""
        result = format_confirmation(cloud_job_info, "cloud")
        assert "Machine type: auto-select" in result

    def test_local_workflow(self, local_workflow_info):
        """Test local workflow: header, sections, paths, docker."""
        result = format_confirmation(local_workflow_info, "local")
        assert result.startswith("Run workflow locally")
        # Expected sections
        assert "[Configuration]" in result
        assert "[Paths]" in result
        assert "[Workflow Details]" in result
        assert "[Docker Image]" in result
        assert "[Google Cloud]" not in result
        assert "[GitHub]" not in result
        # Paths and docker
        assert "Forecast: ./local/forecast/" in result
        assert "Image: epymodelingsuite:dev" in result

    def test_local_job(self, local_job_info):
        """Test local job: header, sections, no resources."""
        result = format_confirmation(local_job_info, "local")
        assert result.startswith("Run Builder locally")
        assert "[Configuration]" in result
        assert "[Paths]" in result
        assert "[Job Details]" in result
        assert "[Docker Image]" in result
        assert "[Resources]" not in result

    def test_defaults(self):
        """Test missing command_type defaults to workflow, run_id to auto-generated."""
        result = format_confirmation({"exp_id": "test"}, "cloud")
        assert result.startswith("Submit workflow")
        assert "<auto-generated>" in result

    def test_profile_as_dict(self):
        """Test dict profile uses profile['name']."""
        info = {"exp_id": "test", "profile": {"name": "flu", "path": "/some/path"}}
        result = format_confirmation(info, "cloud")
        assert "Profile: flu" in result

    def test_image_uri_without_slash(self):
        """Test image URI without '/' is shown as-is."""
        info = {"command_type": "workflow", "exp_id": "test", "image_uri": "myimage:latest"}
        result = format_confirmation(info, "cloud")
        assert "myimage:latest" in result
        assert "Registry:" not in result


class TestPromptConfirmation:
    """Test prompt_confirmation() user interaction."""

    def test_auto_confirm_returns_true(self, capsys):
        """Test auto_confirm=True skips prompt and returns True."""
        assert prompt_confirmation("msg", auto_confirm=True) is True
        captured = capsys.readouterr()
        assert "Auto-confirmed" in captured.out

    def test_input_y(self):
        """Test 'y' input returns True."""
        with patch("builtins.input", return_value="y"):
            assert prompt_confirmation("msg") is True

    def test_input_yes(self):
        """Test 'yes' input returns True."""
        with patch("builtins.input", return_value="yes"):
            assert prompt_confirmation("msg") is True

    def test_input_n(self):
        """Test 'n' input returns False."""
        with patch("builtins.input", return_value="n"):
            assert prompt_confirmation("msg") is False

    def test_input_empty(self):
        """Test empty input returns False."""
        with patch("builtins.input", return_value=""):
            assert prompt_confirmation("msg") is False

    def test_keyboard_interrupt(self):
        """Test KeyboardInterrupt returns False."""
        with patch("builtins.input", side_effect=KeyboardInterrupt):
            assert prompt_confirmation("msg") is False

    def test_eof_error(self):
        """Test EOFError returns False."""
        with patch("builtins.input", side_effect=EOFError):
            assert prompt_confirmation("msg") is False
